version: '3.3'

services:
  wordpress:
      image: where-one-eats-two-eats-landing
      container_name: wordpress
      environment:
        DB_HOST: $MYSQL_HOST:$MYSQL_PORT
        DB_USER: $MYSQL_WP_USER
        DB_PASSWORD: $MYSQL_WP_PASSWORD
        DB_NAME: $WORDPRESS_DB_NAME
        AUTH_KEY: $RANDOM_KEY
        SECURE_AUTH_KEY: $RANDOM_KEY
        NONCE_KEY: $RANDOM_KEY
        LOGGED_IN_KEY: $RANDOM_KEY
        AUTH_SALT: $RANDOM_KEY
        SECURE_AUTH_SALT: $RANDOM_KEY
        LOGGED_IN_SALT: $RANDOM_KEY
        NONCE_SALT: $RANDOM_KEY
        DISABLE_WP_CRON: 'true'
        TZ: America/Lima
      ports:
       - "80:80"
  wordpress-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: wordpress-db
    ports:
     - "$MYSQL_PORT:3306"
    volumes:
     - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: $MYSQL_WP_USER
      MYSQL_PASSWORD: $MYSQL_WP_PASSWORD
      MYSQL_DATABASE: $WORDPRESS_DB_NAME
      TZ: America/Lima
