version: '2'

services:
  db:
    container_name:  database
    image: mariadb  # Pull mysql image from Docker Hub
    ports:  # Set up ports exposed for other containers to connect to
      - "3306:3306"
    volumes:
      - ./dep/mysql:/docker-entrypoint-initdb.d
    environment:  # Set up mysql database name and password
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    image: dondecomeunocomendos/covid19
    container_name: wordpress
    depends_on:
      - db
    ports:
      - "80:80"
    links:
      - db
    restart: always
    environment:
      DB_HOST: db:3306
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_NAME: wordpress
      AUTH_KEY: $(uuidgen)
      SECURE_AUTH_KEY: $(uuidgen)
      NONCE_KEY: $(uuidgen)
      LOGGED_IN_KEY: $(uuidgen)
      AUTH_SALT: $(uuidgen)
      SECURE_AUTH_SALT: $(uuidgen)
      LOGGED_IN_SALT: $(uuidgen)
      NONCE_SALT: $(uuidgen)
      DISABLE_WP_CRON: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - "8080:80"
    environment:
     - PMA_ARBITRARY=1
